version: '3.8'

volumes:
  pg-lab3:

services:
  lab3_db:
    image: 'postgres:13'
    container_name: 'java-postgres-lab3'
    restart: always
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=lab3'
    volumes:
      - pg-lab3:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
